### ISSUE TITLE
Document needs to be closed

### ISSUE THREAD

**Issue by twsouthwick** [mhmd-azeez/OpenXmlDemo#1]
The stream does not have data because you need to close the package. It appears to be uncommented at the moment. Ideally, this would be done with a `using` statement. It does seem a bit weird that after Save it is not available - feel free to open an issue to address this.

https://github.com/encrypt0r/OpenXmlDemo/blob/c19ab6e5753c207435d7f189e588d2ec86012b97/OpenXmlDemo/Program.cs#L30

**Comment by mhmd-azeez** [comment]
@twsouthwick Done OfficeDev/Open-XML-SDK#294
